<?php
declare(strict_types=1);

namespace App\Service;

use App\Model\Entity\ConfigurationSet;
use Cake\Datasource\EntityInterface;

/**
 * Class ConfigurationSetManagerService
 * @package App\Service
 * @property \App\Model\Table\ConfigurationSetsTable $ConfigurationSets
 */
class ConfigurationSetManagerService extends AppService implements ConfigurationSetManagerServiceInterface
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->loadModel('ConfigurationSets');
    }

    /**
     * @param string $type
     * @return EntityInterface|ConfigurationSet
     */
    public function getConfiguration(string $type): EntityInterface
    {
        return $this->ConfigurationSets->find()
            ->where(['ConfigurationSets.type' => $type])
            ->orderDesc('ConfigurationSets.created')
            ->first();
    }
}
