version: "3.9"

services:
  cakephp:
    build:
      context: ./docker/devcontainer
      dockerfile: Dockerfile
    container_name: cake
    working_dir: /app
    entrypoint: ["dockerize", "-wait", "file:///app/config/app_local.php", "-wait", "tcp://cakephp_db:5432", "-timeout", "2700s", "-wait-retry-interval", "10s"]
    command: php bin/cake.php server -H 0.0.0.0
    ports:
    - 8765:8765
    volumes:
    - ./:/app
    environment:
      DB_HOST: cakephp_db
      REDIS_HOST: cakephp_redis
      DB_PASSWORD: /run/secrets/db_password
      DB_NAME: /run/secrets/db_name
      DB_USER: /run/secrets/db_user
    secrets:
      - db_password
      - db_user
      - db_name
    depends_on:
      - cakephp-db
      - cakephp-migrate
      - cakephp-redis

  composer:
    build:
      context: ./docker/devcontainer
      dockerfile: Dockerfile
    container_name: composer
    working_dir: /app
    command: composer install
    volumes:
      - ./:/app

  cakephp-migrate:
    build:
      context: ./docker/devcontainer
      dockerfile: Dockerfile
    container_name: cakephp-migrate
    working_dir: /app
    entrypoint: ["dockerize", "-wait", "file:///app/config/app_local.php", "-wait", "tcp://cakephp_db:5432", "-timeout", "2700s", "-wait-retry-interval", "10s"]
    command: php bin/cake.php migrations migrate
    volumes:
      - ./:/app
    environment:
      DB_HOST: cakephp_db
      REDIS_HOST: cakephp_redis
      DB_PASSWORD: /run/secrets/db_password
      DB_NAME: /run/secrets/db_name
      DB_USER: /run/secrets/db_user
    secrets:
      - db_password
      - db_user
      - db_name
    depends_on:
      - cakephp-db
      - composer

  cakephp-db:
    image: postgres:12.4
    container_name: cakephp_db
    volumes:
    - db_data:/var/lib/postgresql/data
    secrets:
    - db_password
    - db_user
    - db_name
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_DB: /run/secrets/db_name

  cakephp-redis:
    image: "redis:alpine"
    container_name: cakephp_redis

volumes:
  db_data:

secrets:
  db_password:
    file: ./postgres_password.txt
  db_user:
    file: ./postgres_user.txt
  db_name:
    file: ./postgres_db_name.txt
