version: "3.9"

services:
  cakephp:
    build:
      context: ./docker/devcontainer
      dockerfile: Dockerfile
    container_name: cake
    working_dir: /app
    command: php bin/cake.php server -H 0.0.0.0
    ports:
    - 8765:8765
    volumes:
    - ./:/app
    environment:
      DB_HOST: cakephp_db
      DB_PASSWORD: /run/secrets/db_password
      DB_NAME: /run/secrets/db_name
      DB_USER: /run/secrets/db_user
    secrets:
      - db_password
      - db_user
      - db_name
    depends_on:
      - cakephp-db

  cakephp-db:
    image: postgres:12.4
    container_name: cakephp_db
    volumes:
    - db_data:/var/lib/postgresql/data
    secrets:
    - db_password
    - db_user
    - db_name
    environment:
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_DB: /run/secrets/db_name

volumes:
  db_data:
  
secrets:
  db_password:
    file: ./postgres_password.txt
  db_user:
    file: ./postgres_user.txt
  db_name:
    file: ./postgres_db_name.txt